server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/OffreDb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: OFFRE-SERVICE

  config:
    import: optional:configserver:http://localhost:9296/




